function chapterGroupsUiPatch_(){return `<style>
.chapter-group-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.chapter-group-card{aspect-ratio:1.12;border-radius:18px;padding:16px;display:flex;flex-direction:column;justify-content:space-between;background:var(--card);border:1px solid var(--line);box-shadow:var(--shadow);cursor:pointer;min-width:0}.chapter-group-card .group-icon{font-size:30px}.chapter-group-card .group-title{font-size:18px;font-weight:900}.chapter-group-card .group-meta{font-size:12px;color:var(--muted);margin-top:4px}.group-list{display:grid;gap:9px}.group-back{margin-bottom:6px}.lecture-reset-card{border-style:dashed}.lecture-reset-title{font-size:22px;font-weight:900;margin:5px 0}.lecture-reset-copy{line-height:1.5}@media(max-width:380px){.chapter-group-grid{gap:9px}.chapter-group-card{padding:13px;border-radius:16px}.chapter-group-card .group-title{font-size:16px}}
</style><script>
(function(){
  function n(v){return String(v||'').trim().toLowerCase();}
  function chapterGroupName(name){
    var x=n(name);
    if(/fraction pattern|triplet|calculation memory|square|cube/.test(x))return 'misc';
    if(/percentage|profit|loss|discount|ratio|proportion|average|mixture|alligation|interest|time.*work|pipe|cistern|speed|distance|train|boat|stream|partnership|ages|work.*wage/.test(x))return 'arithmetic';
    return 'advanced';
  }
  function groupedChapters(){
    var out={advanced:[],arithmetic:[],misc:[]};
    (app.bootstrap.chapters||[]).forEach(function(c){out[chapterGroupName(c.chapter)].push(c);});
    Object.keys(out).forEach(function(k){out[k].sort(function(a,b){return String(a.chapter).localeCompare(String(b.chapter));});});
    return out;
  }
  function groupStats(list){return list.reduce(function(a,c){a.total+=Number(c.total||0);a.mastered+=Number(c.mastered||0);a.active+=Number(c.remaining||0);return a;},{total:0,mastered:0,active:0});}
  function mockSets(){return (app.bootstrap.demandSets||[]).filter(function(s){return String(s.setId)!=='CALC_TRAINING';});}
  function groupPicker(label,mode,opts){
    var modal=$('#modal');modal.className='modal';modal.innerHTML='<div class="sheet"><div class="row between"><div><div class="eyebrow">'+esc(label)+'</div><div class="quiz-title">How many questions?</div></div><button class="iconbtn" id="groupClose">×</button></div><div class="practice-actions" style="margin-top:16px"><button class="btn soft" data-group-count="10">10</button><button class="btn soft" data-group-count="20">20</button><button class="btn soft" data-group-count="25">25</button></div></div>';
    $('#groupClose').onclick=closeModal;modal.querySelectorAll('[data-group-count]').forEach(function(b){b.onclick=function(){closeModal();beginQuiz(mode,Object.assign({},opts,{count:Number(b.dataset.groupCount)}));};});
  }
  function groupActions(title,opts){
    return '<div class="practice-actions"><button class="btn ghost" data-group-mode="all">📚 Practice All</button><button class="btn soft" data-group-mode="random">🔀 Random</button><button class="btn ghost" data-group-mode="weak">🎯 Weak</button></div>';
  }
  function bindGroupActions(root,title,opts){root.querySelectorAll('[data-group-mode]').forEach(function(b){b.onclick=function(){var m=b.dataset.groupMode;if(m==='all')beginQuiz('group_complete',opts);else groupPicker(title+(m==='weak'?' · Weak':' · Random'),m==='weak'?'group_weak':'group_random',opts);};});}
  window.openStudyGroup=function(key){
    var groups=groupedChapters(),list=groups[key]||[];var labels={advanced:['Advanced','△'],arithmetic:['Arithmetic','%'],misc:['MISC','▦']};var meta=labels[key]||[key,'▤'];var stats=groupStats(list);app.view='chapters';nav('chapters');
    var extra='';if(key==='misc')extra='<div class="list-card topic-row" data-misc-generated="Squares"><div class="row between"><div><b>Squares</b><div class="muted">Generated calculation-memory practice</div></div><span class="tag">Open</span></div></div><div class="list-card topic-row" data-misc-generated="Cubes"><div class="row between"><div><b>Cubes</b><div class="muted">Generated calculation-memory practice</div></div><span class="tag">Open</span></div></div>';
    var empty=!list.length&&key!=='misc';
    var summary=empty?'<div class="card lecture-reset-card"><div class="eyebrow">Fresh lecture bank</div><div class="lecture-reset-title">Ready for your first '+esc(meta[0])+' lecture</div><div class="muted lecture-reset-copy">New lecture concepts and questions will appear here automatically after they are added to the active database.</div></div>':'<div class="card"><div class="hub-stats"><div class="hub-stat"><b>'+stats.total+'</b><span class="muted">Total</span></div><div class="hub-stat"><b>'+stats.mastered+'</b><span class="muted">Mastered</span></div><div class="hub-stat"><b>'+stats.active+'</b><span class="muted">Active</span></div></div>'+groupActions(meta[0],{})+'</div>';
    $('#main').innerHTML='<div class="content"><button class="btn ghost group-back" id="groupBack">← Practice Hub</button><div class="section-title">'+esc(meta[0]).toUpperCase()+'</div>'+summary+'<div class="section-title">'+(key==='misc'?'Practice Banks':'Chapters')+'</div><div class="group-list">'+extra+list.map(function(c){return '<div class="list-card topic-row" data-group-chapter="'+esc(c.chapter)+'"><div class="row between"><div><b>'+esc(c.chapter)+'</b><div class="muted">'+Number(c.total||0)+' total · '+Number(c.mastered||0)+' mastered · '+Number(c.remaining||0)+' active</div></div><span class="tag">Open</span></div></div>';}).join('')+(empty?'<div class="muted" style="padding:4px">No active lecture chapter yet.</div>':'')+'</div></div>';
    $('#groupBack').onclick=window.chapters;var chapterNames=list.map(function(c){return c.chapter;});if(!empty)bindGroupActions($('#main'),meta[0],{groupName:meta[0],chapters:chapterNames});
    $('#main').querySelectorAll('[data-group-chapter]').forEach(function(card){card.onclick=function(){openChapterHub(card.dataset.groupChapter);};});
    $('#main').querySelectorAll('[data-misc-generated]').forEach(function(card){card.onclick=function(){openMiscGenerated(card.dataset.miscGenerated);};});window.scrollTo(0,0);
  };
  window.openMiscGenerated=function(topic){app.view='chapters';nav('chapters');var opts={groupName:topic,source:'generated',generatedChapter:'Calculation Memory',generatedTopic:topic};$('#main').innerHTML='<div class="content"><button class="btn ghost group-back" id="miscBack">← MISC</button><div class="section-title">MISC → '+esc(topic).toUpperCase()+'</div><div class="card">'+groupActions(topic,opts)+'</div></div>';$('#miscBack').onclick=function(){openStudyGroup('misc');};bindGroupActions($('#main'),topic,opts);window.scrollTo(0,0);};
  window.openMocksGroup=function(){var sets=mockSets();app.view='chapters';nav('chapters');$('#main').innerHTML='<div class="content"><button class="btn ghost group-back" id="mockBack">← Practice Hub</button><div class="section-title">MOCKS</div><div class="card"><div class="muted">Saved mock sets. Open any set for Practice All, Random and Weak, plus its chapter and calculative categories.</div></div><div class="section-title">Mock Sets</div><div class="group-list">'+(sets.map(function(s){return '<div class="list-card topic-row" data-mock-set="'+esc(s.setId)+'"><div class="row between"><div><b>'+esc(s.name)+'</b><div class="muted">'+Number(s.count||0)+' questions</div></div><span class="tag">Open</span></div></div>';}).join('')||'<div class="card muted">No mock set added yet.</div>')+'</div></div>';$('#mockBack').onclick=window.chapters;$('#main').querySelectorAll('[data-mock-set]').forEach(function(card){card.onclick=function(){openDemandSetHub(card.dataset.mockSet);};});window.scrollTo(0,0);};
  window.chapters=function(){var groups=groupedChapters(),a=groupStats(groups.advanced),r=groupStats(groups.arithmetic),m=groupStats(groups.misc),mock=mockSets();app.view='chapters';nav('chapters');$('#main').innerHTML='<div class="content"><div class="section-title">Practice Hub</div><div class="chapter-group-grid"><div class="chapter-group-card" data-study-group="advanced"><div class="group-icon">△</div><div><div class="group-title">Advanced</div><div class="group-meta">'+groups.advanced.length+' chapters · '+a.active+' active</div></div></div><div class="chapter-group-card" data-study-group="arithmetic"><div class="group-icon">%</div><div><div class="group-title">Arithmetic</div><div class="group-meta">'+groups.arithmetic.length+' chapters · '+r.active+' active</div></div></div><div class="chapter-group-card" data-study-group="misc"><div class="group-icon">▦</div><div><div class="group-title">MISC</div><div class="group-meta">Squares, cubes, fractions, triplets + more</div></div></div><div class="chapter-group-card" id="mocksGroup"><div class="group-icon">◫</div><div><div class="group-title">Mocks</div><div class="group-meta">'+mock.length+' saved set'+(mock.length===1?'':'s')+'</div></div></div></div></div>';$('#main').querySelectorAll('[data-study-group]').forEach(function(card){card.onclick=function(){openStudyGroup(card.dataset.studyGroup);};});$('#mocksGroup').onclick=openMocksGroup;window.scrollTo(0,0);};
  var oldHome=home;
  window.home=function(){
    var d=app.bootstrap&&app.bootstrap.dashboard||{},l=app.bootstrap&&app.bootstrap.library||{};
    if(d.scheduleReady!==false){oldHome();return;}
    app.view='home';nav('home');$('#nav').classList.remove('hidden');
    $('#main').innerHTML='<div class="content grid"><div class="card hero"><div class="eyebrow">Lecture bank reset</div><h2>Ready for fresh Maths content</h2><div class="muted">Advanced and Arithmetic will now grow only from the lecture concepts and question sets you add.</div></div><div class="section-title">Study</div><div class="grid2"><div class="card action-card" onclick="showView(\'chapters\')"><div class="action-icon">📚</div><div><div class="action-title">Practice Hub</div><div class="muted" style="font-size:12px">Advanced · Arithmetic · MISC · Mocks</div></div></div><div class="card action-card" onclick="showView(\'library\')"><div class="action-icon">🧠</div><div><div class="action-title">Library</div><div class="muted" style="font-size:12px">Active lecture material only</div></div></div><div class="card action-card" onclick="showView(\'ondemand\')"><div class="action-icon">◆</div><div><div class="action-title">On Demand</div><div class="muted" style="font-size:12px">Calculation + quick practice</div></div></div><div class="card action-card" onclick="showView(\'progress\')"><div class="action-icon">📊</div><div><div class="action-title">Progress</div><div class="muted" style="font-size:12px">Fresh-bank progress</div></div></div></div><div class="section-title">MISC revision</div><div class="grid2"><button class="btn ghost" onclick="beginQuiz(\'library\',{cluster:\'Fractions\'})">⅞ Fractions · '+Number(l.fractions||0)+'</button><button class="btn ghost" onclick="beginQuiz(\'library\',{cluster:\'Triplets\'})">△ Triplets · '+Number(l.triplets||0)+'</button></div><div class="card lecture-reset-card"><div class="eyebrow">Next step</div><b>Add a lecture in the Maths Content chat</b><div class="muted" style="font-size:12px;margin-top:5px">Example: Advanced → Coordinate Geometry → Concepts / Questions. Random, Weak and Practice All will use the same existing logic.</div></div></div>';window.scrollTo(0,0);
  };
  var oldShowView=showView;
  window.showView=function(v){
    if(v==='chapters'){app.view='chapters';nav('chapters');window.chapters();return;}
    return oldShowView(v);
  };
})();
</script>`;}
