function completePracticeUiPatch_(){return `<style>
.quiz-jump-tag{cursor:pointer;user-select:none}.question-jump-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-top:14px}.question-jump-grid button{padding:10px 4px}.question-jump-grid .qj-correct{background:var(--okbg);color:var(--ok);border-color:color-mix(in srgb,var(--ok) 45%,var(--line))}.question-jump-grid .qj-wrong{background:var(--badbg);color:var(--bad);border-color:color-mix(in srgb,var(--bad) 45%,var(--line))}.question-jump-grid .qj-seen{background:var(--warnbg);color:var(--warn);border-color:color-mix(in srgb,var(--warn) 45%,var(--line))}.question-jump-grid .qj-current{outline:2px solid var(--primary);outline-offset:1px}.resume-card{background:var(--primary2);border:1px solid var(--line);border-radius:14px;padding:14px;margin-top:12px}.resume-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.v2-actions{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.v2-actions .btn{min-height:46px;font-size:12px}.v2-chapter-card{border:1px solid var(--line);border-radius:16px;background:var(--card);padding:14px;cursor:pointer}.v2-progress{height:6px;background:var(--line);border-radius:999px;overflow:hidden;margin-top:9px}.v2-progress>i{display:block;height:100%;background:var(--primary);border-radius:999px}.v2-topic-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.v2-topic-card{border:1px solid var(--line);border-radius:16px;background:var(--card);padding:16px;cursor:pointer}.v2-topic-card b{font-size:17px}.v2-home-stat{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin-top:12px}.v2-home-stat>div{background:rgba(255,255,255,.13);border-radius:11px;padding:9px;text-align:center}.v2-home-stat b{display:block;font-size:18px}.v2-mini-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.v2-stat-card{padding:13px;border:1px solid var(--line);border-radius:15px;background:var(--card);cursor:pointer}.v2-stat-card b{font-size:20px;display:block}.v2-metric-row{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.v2-metric{padding:11px 7px;border-radius:12px;background:var(--primary2);text-align:center}.v2-metric b{display:block;font-size:19px}.v2-star-item{border:1px solid var(--line);border-radius:13px;padding:11px;background:var(--card)}.v2-badge{display:inline-flex;padding:4px 7px;border-radius:999px;font-size:10px;font-weight:850;margin-right:4px}.v2-badge.star{background:var(--warnbg);color:var(--warn)}.v2-badge.diff{background:var(--badbg);color:var(--bad)}
@media(max-width:390px){.question-jump-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.resume-actions{grid-template-columns:1fr}.v2-actions{grid-template-columns:repeat(2,minmax(0,1fr))}.v2-topic-grid{grid-template-columns:1fr}.v2-mini-grid{grid-template-columns:1fr}}
</style><script>
(function(){
  const V2CACHE='maths-v2:';
  function v2get(k){try{return JSON.parse(localStorage.getItem(V2CACHE+k)||'null')}catch(e){return null}}
  function v2set(k,v){try{localStorage.setItem(V2CACHE+k,JSON.stringify(v))}catch(e){}return v}
  function v2drop(k){try{localStorage.removeItem(V2CACHE+k)}catch(e){}}
  function v2call(fn){var args=[].slice.call(arguments,1);return new Promise(function(resolve,reject){var r=google.script.run.withSuccessHandler(resolve).withFailureHandler(function(e){reject(new Error(e&&e.message?e.message:String(e)))});if(fn==='getMathsV2Bootstrap')r.getMathsV2Bootstrap();else if(fn==='getMathsProgressV2')r.getMathsProgressV2();else if(fn==='getStarredRevisionV2')r.getStarredRevisionV2();else if(fn==='startMathsV2Quiz')r.startMathsV2Quiz(args[0]);else if(fn==='toggleImportantV2')r.toggleImportantV2(args[0],args[1]);else if(fn==='toggleDifficultV2')r.toggleDifficultV2(args[0],args[1]);else if(fn==='getSessionAttemptMapV2')r.getSessionAttemptMapV2(args[0]);else reject(new Error('Unknown V2 function'))})}
  window.MathV2={call:v2call,get:v2get,set:v2set,drop:v2drop};

  function isCompletePractice(mode,opts){mode=String(mode||'');opts=opts||{};if(mode==='chapter_complete'||mode==='topic_complete'||mode==='group_complete')return true;return mode==='demand_set'&&String(opts.practiceMode||'all').toLowerCase()==='all'&&String(opts.setId||'')!=='CALC_TRAINING'}
  var baseBeginQuiz=window.beginQuiz;
  function startFreshComplete(mode,opts){closeModal();return baseBeginQuiz(mode,Object.assign({},opts||{}))}
  window.beginQuiz=async function(mode,opts){opts=opts||{};if(!isCompletePractice(mode,opts)||opts.__skipCompleteResume)return baseBeginQuiz(mode,opts);loading(true);try{var req=Object.assign({mode:mode},opts),cp=await server('getPracticeCheckpoint',req);loading(false);if(!cp||!cp.hasProgress)return baseBeginQuiz(mode,opts);var modal=$('#modal');modal.className='modal';modal.innerHTML='<div class="sheet"><div class="row between"><div><div class="eyebrow">Complete Practice</div><div class="quiz-title">Continue this bank?</div></div><button class="iconbtn" id="completeResumeClose">×</button></div><div class="resume-card"><b>'+esc(cp.title||'Complete Practice')+'</b><div class="muted" style="margin-top:4px">Last position: Question '+Number(cp.resumeQuestion)+' of '+Number(cp.total)+'</div><div class="resume-actions"><button class="btn primary" id="completeResumeBtn">Resume from Q'+Number(cp.resumeQuestion)+'</button><button class="btn ghost" id="completeRestartBtn">Start from Q1</button></div></div><div class="muted" style="font-size:12px;margin-top:12px">Tap the question counter anytime to jump directly to a question.</div></div>';$('#completeResumeClose').onclick=closeModal;$('#completeResumeBtn').onclick=function(){closeModal();resumeQuiz(cp.sessionId)};$('#completeRestartBtn').onclick=function(){startFreshComplete(mode,opts)}}catch(e){loading(false);return baseBeginQuiz(mode,opts)}};

  window.openQuestionJump=async function(){if(!app.quiz||!app.quiz.questions||!app.quiz.questions.length)return;var total=app.quiz.questions.length,current=app.quiz.index+1,results={};try{results=await v2call('getSessionAttemptMapV2',app.quiz.sessionId)}catch(e){}var modal=$('#modal');modal.className='modal',buttons='';for(var i=1;i<=total;i++){var q=app.quiz.questions[i-1],id=String(q.questionId||''),state=results[id]||'',cls=state==='correct'?'qj-correct':state==='wrong'?'qj-wrong':state==='seen'?'qj-seen':'';if(i===current)cls+=' qj-current';buttons+='<button class="btn ghost '+cls+'" data-jump-q="'+i+'">'+i+'</button>'}modal.innerHTML='<div class="sheet"><div class="row between"><div><div class="eyebrow">Question selector</div><div class="quiz-title">Jump to question</div></div><button class="iconbtn" id="jumpClose">×</button></div><div class="muted" style="font-size:12px;margin-top:4px"><span style="color:var(--ok)">● Correct</span> · <span style="color:var(--bad)">● Wrong</span> · <span style="color:var(--warn)">● Revealed</span> · Neutral unanswered</div><div class="question-jump-grid">'+buttons+'</div></div>';$('#jumpClose').onclick=closeModal;modal.querySelectorAll('[data-jump-q]').forEach(function(btn){btn.onclick=function(){var target=Math.max(1,Math.min(total,Number(btn.dataset.jumpQ||1)));closeModal();app.quiz.index=target-1;app.qStart=Date.now();renderQuestion();window.scrollTo(0,0);server('saveSessionPosition',app.quiz.sessionId,app.quiz.index).catch(function(){})}})};

  function countPicker(title,req){var modal=$('#modal');modal.className='modal';modal.innerHTML='<div class="sheet"><div class="row between"><div><div class="eyebrow">'+esc(title)+'</div><div class="quiz-title">How many questions?</div></div><button class="iconbtn" id="v2CountClose">×</button></div><div class="v2-actions" style="margin-top:15px"><button class="btn soft" data-v2count="10">10</button><button class="btn soft" data-v2count="20">20</button><button class="btn soft" data-v2count="25">25</button></div></div>';$('#v2CountClose').onclick=closeModal;modal.querySelectorAll('[data-v2count]').forEach(function(b){b.onclick=function(){closeModal();startV2(Object.assign({},req,{count:Number(b.dataset.v2count)}))}})}
  async function startV2(req){loading(true);try{var s=await v2call('startMathsV2Quiz',req);loading(false);if(!s||s.ok===false){toast((s&&s.message)||'No eligible questions');return}openQuiz(s)}catch(e){loading(false);toast(e.message||e)}}
  function sixActions(req){return '<div class="v2-actions"><button class="btn soft" data-v2kind="random">🔀 Random</button><button class="btn ghost" data-v2kind="weak">🎯 Weak</button><button class="btn ghost" data-v2kind="all">📚 Practice All</button><button class="btn ghost" data-v2kind="new">🆕 New</button><button class="btn ghost" data-v2kind="starred">⭐ Starred</button><button class="btn warn" data-v2kind="difficult">🔥 Difficult</button></div>'}
  function bindSix(root,req){root.querySelectorAll('[data-v2kind]').forEach(function(b){b.onclick=function(){var kind=b.dataset.v2kind,r=Object.assign({},req,{kind:kind});if(kind==='all')startV2(r);else countPicker((req.title||req.chapter||req.majorTopic||'Practice')+' · '+b.textContent.trim(),r)}})}

  var baseOpenChapterHub=window.openChapterHub;
  window.openChapterHub=function(chapter){var c=(app.bootstrap.chapters||[]).find(function(x){return String(x.chapter)===String(chapter)});if(!c)return baseOpenChapterHub(chapter);app.view='chapters';nav('chapters');var topics=c.majorTopics||[],attempted=Math.max(0,Number(c.total||0)-Number(c.remaining||0));var pct=Number(c.total||0)?Math.round(attempted*100/Number(c.total)):0;$('#main').innerHTML='<div class="content"><button class="btn ghost" id="v2ChapterBack">← Chapters</button><div style="margin:14px 2px 12px"><div class="eyebrow">Chapter</div><div class="quiz-title" style="font-size:25px">'+esc(chapter)+'</div><div class="muted" style="margin-top:4px">'+Number(c.total||0)+' cards · '+Number(c.remaining||0)+' active</div><div class="v2-progress"><i style="width:'+pct+'%"></i></div></div><div class="card">'+sixActions({})+'</div><div class="section-title">Study banks</div><div class="v2-topic-grid">'+topics.map(function(t){return '<div class="v2-topic-card" data-v2topic="'+esc(t.key||t.name)+'"><b>'+esc(t.name)+'</b><div class="muted" style="margin-top:5px">'+Number(t.total||0)+' cards · '+Number(t.active||0)+' active</div></div>'}).join('')+'</div></div>';$('#v2ChapterBack').onclick=chapters;bindSix($('#main'),{scope:'chapter',chapter:chapter,title:chapter});$('#main').querySelectorAll('[data-v2topic]').forEach(function(card){card.onclick=function(){openTopicHub(chapter,card.dataset.v2topic)}});window.scrollTo(0,0)};

  var baseOpenTopicHub=window.openTopicHub;
  window.openTopicHub=function(chapter,key){var c=(app.bootstrap.chapters||[]).find(function(x){return String(x.chapter)===String(chapter)}),t=c&&(c.majorTopics||[]).find(function(x){return String(x.key||x.name)===String(key)});if(!t)return baseOpenTopicHub(chapter,key);app.view='chapters';nav('chapters');$('#main').innerHTML='<div class="content"><button class="btn ghost" id="v2TopicBack">← '+esc(chapter)+'</button><div style="margin:14px 2px 12px"><div class="eyebrow">'+esc(chapter)+'</div><div class="quiz-title" style="font-size:24px">'+esc(t.name)+'</div><div class="muted" style="margin-top:4px">'+Number(t.total||0)+' cards · '+Number(t.active||0)+' active</div></div><div class="card">'+sixActions({})+'</div></div>';$('#v2TopicBack').onclick=function(){openChapterHub(chapter)};bindSix($('#main'),{scope:'topic',chapter:chapter,majorTopic:t.key||t.name,title:chapter+' · '+t.name});window.scrollTo(0,0)};

  var baseOpenStudyGroup=window.openStudyGroup;
  window.openStudyGroup=function(key){baseOpenStudyGroup(key);setTimeout(function(){var groups=(app.bootstrap.chapters||[]).filter(function(c){var x=String(c.chapter||'').toLowerCase();if(key==='misc')return /fraction pattern|triplet|calculation memory|square|cube/.test(x);if(key==='arithmetic')return /percentage|profit|loss|discount|ratio|proportion|average|mixture|alligation|interest|time.*work|pipe|cistern|speed|distance|train|boat|stream|partnership|ages|work.*wage/.test(x);return !/fraction pattern|triplet|calculation memory|square|cube|percentage|profit|loss|discount|ratio|proportion|average|mixture|alligation|interest|time.*work|pipe|cistern|speed|distance|train|boat|stream|partnership|ages|work.*wage/.test(x)}),old=$('#main .practice-actions');if(old){var wrap=old.parentElement;old.outerHTML=sixActions({});bindSix(wrap,{scope:'group',chapters:groups.map(function(c){return c.chapter}),groupName:key,title:key.charAt(0).toUpperCase()+key.slice(1)})}},0)};

  var baseRenderQuestion=window.renderQuestion;
  window.renderQuestion=function(){baseRenderQuestion();if(!app.quiz)return;var counter=document.querySelector('.quiz-head .tag');if(counter){counter.classList.add('quiz-jump-tag');counter.setAttribute('role','button');counter.setAttribute('tabindex','0');counter.setAttribute('aria-label','Jump to question');counter.textContent='Q '+(app.quiz.index+1)+'/'+app.quiz.questions.length+' ▾';counter.onclick=window.openQuestionJump;counter.onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();window.openQuestionJump()}}}var q=app.quiz.questions[app.quiz.index],tools=document.querySelector('.dock-tools');if(!tools||!q)return;var buttons=[].slice.call(tools.querySelectorAll('button'));buttons.forEach(function(b){var tx=(b.textContent||'').toLowerCase();if(tx.indexOf('master')>=0)b.style.display='none';if(tx.indexOf('mark')>=0||tx.indexOf('star')>=0){b.textContent=(q.important||q.marked)?'⭐ Important':'☆ Important';b.onclick=async function(){try{var r=await v2call('toggleImportantV2',q.questionId,app.quiz.sessionId);q.important=r.important;q.marked=r.important;b.textContent=r.important?'⭐ Important':'☆ Important';v2drop('home');v2drop('starred')}catch(e){toast(e.message||e)}}}});if(!tools.querySelector('[data-v2-difficult]')){var d=document.createElement('button');d.className='btn '+(q.difficult?'warn':'ghost');d.setAttribute('data-v2-difficult','1');d.textContent=q.difficult?'🔥 Difficult':'◇ Difficult';d.onclick=async function(){try{var r=await v2call('toggleDifficultV2',q.questionId,app.quiz.sessionId);q.difficult=r.difficult;d.className='btn '+(r.difficult?'warn':'ghost');d.textContent=r.difficult?'🔥 Difficult':'◇ Difficult';v2drop('home');v2drop('starred')}catch(e){toast(e.message||e)}};tools.appendChild(d)}};

  var baseSaveAndHome=window.saveAndHome;window.saveAndHome=function(){if(app.quiz&&app.quiz.sessionId)server('saveSessionPosition',app.quiz.sessionId,app.quiz.index).catch(function(){});v2drop('home');v2drop('progress');return baseSaveAndHome()};

  async function loadHomeFresh(render){try{var b=await v2call('getMathsV2Bootstrap');v2set('home',b);if(render)renderHomeV2(b)}catch(e){}}
  function renderHomeV2(b){if(!b)return;var d=app.bootstrap&&app.bootstrap.dashboard||{},sched=b.schedule,hasDay=sched&&Number(sched.day)>0&&sched.chapter;var resume=app.bootstrap&&app.bootstrap.resume;$('#main').innerHTML='<div class="content grid"><div class="card hero"><div class="eyebrow">Today’s Maths</div><h2>'+(hasDay?'Day '+Number(sched.day)+' · '+esc(sched.chapter):'Ready for today')+'</h2><div class="muted">Daily target · '+Number(b.dailyTarget||20)+' questions</div><div class="v2-home-stat"><div><b>'+Number(b.newCount||0)+'</b><span>New</span></div><div><b>'+Number(b.starred||0)+'</b><span>Starred</span></div><div><b>'+Number(b.difficult||0)+'</b><span>Difficult</span></div></div>'+(hasDay?'<button class="btn primary" style="width:100%;margin-top:13px" onclick="startDaily('+Number(sched.day)+')">Start today’s 20</button>':'<button class="btn primary" style="width:100%;margin-top:13px" onclick="showView(\'chapters\')">Open Practice Hub</button>')+'</div>'+(resume?'<div class="card" onclick="resumeQuiz(\''+esc(resume.sessionId)+'\')" style="cursor:pointer"><div class="eyebrow">Continue practice</div><b>'+esc(resume.title||'Saved session')+'</b><div class="muted" style="margin-top:4px">Resume Q'+(Number(resume.currentIndex||0)+1)+'/'+Number(resume.total||0)+'</div></div>':'')+'<div class="v2-mini-grid"><div class="v2-stat-card" onclick="openGlobalNewV2()"><span>🆕</span><b>'+Number(b.newCount||0)+'</b><div>New Practice</div><div class="muted">Unseen lecture material</div></div><div class="v2-stat-card" onclick="openStarredRevisionV2()"><span>⭐</span><b>'+Number(b.starred||0)+'</b><div>Starred Revision</div><div class="muted">'+Number(b.difficult||0)+' difficult</div></div></div><div class="card"><div class="row between"><div><b>Progress</b><div class="muted">Coverage '+Number(b.coverage||0)+'% · Accuracy '+Number(b.accuracy||0)+'%</div></div><button class="btn ghost" onclick="showView(\'progress\')">Open</button></div></div></div>'}
  var baseHome=window.home;window.home=function(){app.view='home';nav('home');var cached=v2get('home');if(cached)renderHomeV2(cached);else baseHome();loadHomeFresh(true)};

  window.openGlobalNewV2=async function(){app.view='home';nav('home');loading(true);try{var p=await v2call('getMathsProgressV2');loading(false);var rows=(p.chapters||[]).filter(function(c){return Number(c.metric&&c.metric.unseen||0)>0});$('#main').innerHTML='<div class="content"><button class="btn ghost" id="newBack">← Home</button><div style="margin:14px 2px"><div class="eyebrow">New Practice</div><div class="quiz-title">Unseen questions</div><div class="muted">Fresh material you have not attempted yet.</div></div><div class="list">'+rows.map(function(c){return '<div class="v2-chapter-card" data-newchapter="'+esc(c.chapter)+'"><div class="row between"><b>'+esc(c.chapter)+'</b><span class="tag">'+Number(c.metric.unseen||0)+' new</span></div></div>'}).join('')+'</div></div>';$('#newBack').onclick=home;$('#main').querySelectorAll('[data-newchapter]').forEach(function(x){x.onclick=function(){countPicker(x.dataset.newchapter+' · New',{scope:'chapter',chapter:x.dataset.newchapter,title:x.dataset.newchapter,kind:'new'})}})}catch(e){loading(false);toast(e.message||e)}};

  window.openStarredRevisionV2=async function(){app.view='library';nav('library');var cached=v2get('starred');if(cached)renderStarred(cached);loading(!cached);try{var h=await v2call('getStarredRevisionV2');loading(false);v2set('starred',h);renderStarred(h)}catch(e){loading(false);if(!cached)toast(e.message||e)}};
  function renderStarred(h){$('#main').innerHTML='<div class="content"><button class="btn ghost" id="starBack">← Library</button><div style="margin:14px 2px"><div class="eyebrow">Revision</div><div class="quiz-title">⭐ Starred Revision</div><div class="muted">Important and difficult questions in one place.</div></div><div class="v2-metric-row"><div class="v2-metric"><b>'+Number(h.stats.total||0)+'</b><span>Total</span></div><div class="v2-metric"><b>'+Number(h.stats.important||0)+'</b><span>Important</span></div><div class="v2-metric"><b>'+Number(h.stats.difficult||0)+'</b><span>Difficult</span></div></div><div class="card" style="margin-top:10px">'+sixActions({})+'</div><div class="section-title">Recent starred</div><div class="list">'+(h.items||[]).slice(0,40).map(function(x){return '<div class="v2-star-item"><div><b>'+esc(x.chapter||'Maths')+'</b><span style="float:right">'+(x.important?'<span class="v2-badge star">Important</span>':'')+(x.difficult?'<span class="v2-badge diff">Difficult</span>':'')+'</span></div><div class="muted" style="margin-top:5px">'+esc(x.question||x.topic||x.id)+'</div><div class="muted" style="font-size:10px;margin-top:4px">Day '+Number(x.day||1)+'</div></div>'}).join('')+'</div></div>';$('#starBack').onclick=library;var actionCard=$('#main .card');bindSix(actionCard,{scope:'group',chapters:(app.bootstrap.chapters||[]).map(function(c){return c.chapter}),title:'Starred Revision'});actionCard.querySelector('[data-v2kind="all"]')?.remove();actionCard.querySelector('[data-v2kind="new"]')?.remove();actionCard.querySelector('[data-v2kind="random"]')?.setAttribute('data-v2kind','starred');actionCard.querySelector('[data-v2kind="weak"]')?.setAttribute('data-v2kind','difficult')}

  var baseLibrary=window.library;window.library=function(){baseLibrary();setTimeout(function(){var content=$('#main .content');if(content&&!content.querySelector('[data-v2starhub]')){var c=document.createElement('div');c.className='card';c.setAttribute('data-v2starhub','1');c.style.cursor='pointer';c.innerHTML='<div class="row between"><div><b>⭐ Starred Revision</b><div class="muted" style="font-size:12px">Important + difficult questions</div></div><span class="tag">Open</span></div>';c.onclick=openStarredRevisionV2;content.insertBefore(c,content.children[1]||null)}},0)};

  function renderProgressV2(p){app.view='progress';nav('progress');$('#main').innerHTML='<div class="content"><div style="margin:6px 2px 12px"><div class="eyebrow">Performance</div><div class="quiz-title" style="font-size:25px">Maths Progress</div><div class="muted">Coverage, accuracy and difficult areas.</div></div><div class="v2-metric-row"><div class="v2-metric"><b>'+Number(p.overall.coverage||0)+'%</b><span>Coverage</span></div><div class="v2-metric"><b>'+Number(p.overall.accuracy||0)+'%</b><span>Accuracy</span></div><div class="v2-metric"><b>'+Number(p.overall.difficult||0)+'</b><span>Difficult</span></div></div><div class="section-title">Advanced vs Arithmetic</div><div class="v2-mini-grid"><div class="card"><b>Advanced</b><div class="muted">'+Number(p.advanced.coverage||0)+'% covered · '+Number(p.advanced.accuracy||0)+'% accuracy</div></div><div class="card"><b>Arithmetic</b><div class="muted">'+Number(p.arithmetic.coverage||0)+'% covered · '+Number(p.arithmetic.accuracy||0)+'% accuracy</div></div></div><div class="section-title">Chapters</div><div class="list">'+(p.chapters||[]).map(function(c){return '<div class="v2-chapter-card" data-progchapter="'+esc(c.chapter)+'"><div class="row between"><b>'+esc(c.chapter)+'</b><span class="tag">'+Number(c.metric.coverage||0)+'%</span></div><div class="muted" style="margin-top:4px">Accuracy '+Number(c.metric.accuracy||0)+'% · '+Number(c.metric.difficult||0)+' difficult · '+Number(c.metric.unseen||0)+' new</div><div class="v2-progress"><i style="width:'+Number(c.metric.coverage||0)+'%"></i></div></div>'}).join('')+'</div></div>';$('#main').querySelectorAll('[data-progchapter]').forEach(function(c){c.onclick=function(){openChapterHub(c.dataset.progchapter)}})}
  var baseProgress=window.progress;window.progress=function(){var cached=v2get('progress');if(cached)renderProgressV2(cached);else if(baseProgress)baseProgress();v2call('getMathsProgressV2').then(function(p){v2set('progress',p);renderProgressV2(p)}).catch(function(e){if(!cached)toast(e.message||e)})};

  document.addEventListener('DOMContentLoaded',function(){setTimeout(function(){loadHomeFresh(false);v2call('getMathsProgressV2').then(function(p){v2set('progress',p)}).catch(function(){})},1200)});
})();
</script>`;}
