function demandUiPatch_(){return `<script>
function demandSetById(id){return (app.bootstrap.demandSets||[]).find(s=>String(s.setId)===String(id))||null}
function demandCountPicker(setId,practiceMode,scopeType,scopeValue){
  const set=demandSetById(setId);if(!set)return;
  const label=practiceMode==='weak'?'Weak Practice':'Random Practice';
  const buttons=[10,20,25].map(n=>'<button class="btn soft" onclick="runDemandPractice(\''+String(setId).replace(/'/g,"\\'")+'\',\''+practiceMode+'\',\''+scopeType+'\',\''+String(scopeValue||'').replace(/'/g,"\\'")+'\','+n+')">'+n+'</button>').join('');
  $('#modal').className='modal';$('#modal').innerHTML='<div class="sheet"><div class="row between"><div><div class="eyebrow">'+esc(label)+'</div><div class="quiz-title">How many questions?</div></div><button class="iconbtn" onclick="closeModal()">×</button></div><div class="practice-actions" style="margin-top:16px">'+buttons+'</div></div>';
}
function runDemandPractice(setId,practiceMode,scopeType,scopeValue,count){
  closeModal();const o={setId:String(setId),practiceMode:String(practiceMode),activeOnly:practiceMode!=='all'};
  if(count)o.count=Number(count);if(scopeType==='chapter')o.demandChapter=String(scopeValue);if(scopeType==='calculative')o.calculativeOnly=true;
  beginQuiz('demand_set',o);
}
function demandPracticeAction(setId,practiceMode,scopeType,scopeValue){if(practiceMode==='random'||practiceMode==='weak')demandCountPicker(setId,practiceMode,scopeType,scopeValue);else runDemandPractice(setId,'all',scopeType,scopeValue,0)}
function openDemandSetHub(setId){
  const set=demandSetById(setId);if(!set){toast('Demand set not found.');return}app.view='demand_hub';nav('ondemand');
  const scopeButtons=(type,value)=>'<div class="practice-actions"><button class="btn ghost" onclick="demandPracticeAction(\''+esc(set.setId)+'\',\'all\',\''+type+'\',\''+esc(value||'')+'\')">📚 Practice All</button><button class="btn soft" onclick="demandPracticeAction(\''+esc(set.setId)+'\',\'random\',\''+type+'\',\''+esc(value||'')+'\')">🔀 Random</button><button class="btn ghost" onclick="demandPracticeAction(\''+esc(set.setId)+'\',\'weak\',\''+type+'\',\''+esc(value||'')+'\')">🎯 Weak</button></div>';
  const cats=[];if(Number(set.calculativeCount||0)>0)cats.push('<div class="list-card topic-row" onclick="openDemandCategory(\''+esc(set.setId)+'\',\'calculative\',\'Calculative\')"><div class="row between"><div><b>⚡ Calculative</b><div class="muted">'+set.calculativeCount+' questions · also remain in their chapters</div></div><span class="tag">Open</span></div></div>');
  (set.chapters||[]).forEach(c=>cats.push('<div class="list-card topic-row" onclick="openDemandCategory(\''+esc(set.setId)+'\',\'chapter\',\''+esc(c.name)+'\')"><div class="row between"><div><b>'+esc(c.name)+'</b><div class="muted">'+c.count+' questions</div></div><span class="tag">Open</span></div></div>'));
  $('#main').innerHTML='<div class="content"><button class="btn ghost" onclick="showView(\'ondemand\')">← On Demand</button><div class="section-title">'+esc(set.name).toUpperCase()+'</div><div class="card"><div class="hub-stats"><div class="hub-stat"><b>'+set.count+'</b><span class="muted">Total</span></div><div class="hub-stat"><b>'+Number(set.calculativeCount||0)+'</b><span class="muted">Calculative</span></div><div class="hub-stat"><b>'+((set.chapters||[]).length)+'</b><span class="muted">Chapters</span></div></div>'+scopeButtons('','')+'</div><div class="section-title">Categories</div><div class="list">'+(cats.join('')||'<div class="card muted">No categories yet.</div>')+'</div></div>';window.scrollTo(0,0);
}
function openDemandCategory(setId,type,value){const set=demandSetById(setId);if(!set)return;const count=type==='calculative'?Number(set.calculativeCount||0):(((set.chapters||[]).find(c=>c.name===value)||{}).count||0);$('#main').innerHTML='<div class="content"><button class="btn ghost" onclick="openDemandSetHub(\''+esc(setId)+'\')">← '+esc(set.name)+'</button><div class="section-title">'+esc(set.name).toUpperCase()+' → '+esc(value).toUpperCase()+'</div><div class="card"><div class="hub-stats"><div class="hub-stat"><b>'+count+'</b><span class="muted">Questions</span></div></div><div class="practice-actions"><button class="btn ghost" onclick="demandPracticeAction(\''+esc(setId)+'\',\'all\',\''+type+'\',\''+esc(value)+'\')">📚 Practice All</button><button class="btn soft" onclick="demandPracticeAction(\''+esc(setId)+'\',\'random\',\''+type+'\',\''+esc(value)+'\')">🔀 Random</button><button class="btn ghost" onclick="demandPracticeAction(\''+esc(setId)+'\',\'weak\',\''+type+'\',\''+esc(value)+'\')">🎯 Weak</button></div></div></div>';window.scrollTo(0,0)}
const originalOndemand=ondemand;ondemand=function(){originalOndemand();document.querySelectorAll('[data-set-id]').forEach(btn=>{const id=btn.dataset.setId;if(id&&id!=='CALC_TRAINING'){btn.textContent='Open';btn.onclick=function(){openDemandSetHub(this.dataset.setId)}}})};
</script>`;}
