const MATHS_CORE_VERSION='v9';
const MATHS_CORE_CACHE_SEC=300;
const MATHS_NEW_WINDOW_DAYS=60;

function mathsStudyQuestionsV9_(){return getAllQuestions_().filter(active_);}
function mathsQuestionMapV9_(){const m={};getAllQuestions_().concat(getGeneratedQuestions_()).filter(active_).forEach(q=>{const id=String(q.question_id||'').trim();if(!id)return;if(m[id])throw new Error('Duplicate active Question_ID: '+id);m[id]=q});return m;}
function mathsStateMapV9_(){
  const m={};sheetObjects_(getSheet_(MATHS.SHEETS.STATE)).forEach(r=>{
    const id=String(r.question_id||'').trim();if(!id)return;
    if(!m[id]){m[id]=Object.assign({},r);return}
    const a=m[id],b=r;a.attempts=Math.max(Number(a.attempts||0),Number(b.attempts||0));
    a.mastered=isMastered_(a)||isMastered_(b);a.marked=isMarked_(a)||isMarked_(b);a.difficult=bool_(a.difficult)||bool_(b.difficult);
    const ta=dateMs_(a.last_attempt),tb=dateMs_(b.last_attempt);if(tb>ta){a.last_attempt=b.last_attempt;a.last_result=b.last_result;a.last_response_sec=b.last_response_sec;a.last_variant=b.last_variant;a.last_correct_option=b.last_correct_option}
    if(!a.chapter&&b.chapter)a.chapter=b.chapter;if(!a.topic&&b.topic)a.topic=b.topic;if(!a.subtopic&&b.subtopic)a.subtopic=b.subtopic;
  });return m;
}
function mathsLockedV9_(fn){const l=LockService.getScriptLock();l.waitLock(8000);try{return fn()}finally{l.releaseLock()}}
function mathsVersionV9_(){const p=PropertiesService.getScriptProperties();let v=Number(p.getProperty('MATHS_DATA_VERSION')||1);if(!Number.isFinite(v)||v<1)v=1;return String(v)}
function bumpMathsVersionV9_(){const p=PropertiesService.getScriptProperties();let v=Number(p.getProperty('MATHS_DATA_VERSION')||1);if(!Number.isFinite(v)||v<1)v=1;v++;p.setProperty('MATHS_DATA_VERSION',String(v));return String(v)}
function getMathsCacheVersionV9(){return {version:mathsVersionV9_(),generatedAt:new Date().toISOString()}}
function mathsCacheV9_(){return CacheService.getScriptCache()}
function mathsCacheKeyV9_(name){return 'maths:core:'+MATHS_CORE_VERSION+':'+name+':'+mathsVersionV9_()}
function mathsPctV9_(n,d){return d?Math.round(Number(n||0)*1000/Number(d))/10:0}
function mathsMetricV9_(pool,state){
  state=state||mathsStateMapV9_();const profiles=mathsAttemptProfileMapV20_(false);let attempted=0,wrong=0,difficult=0,starred=0,weak=0,hard=0;
  (pool||[]).forEach(q=>{const s=state[String(q.question_id)]||{},a=Number(s.attempts||0),last=normalizeLabel_(s.last_result);if(a>0)attempted++;if(last==='wrong')wrong++;if(bool_(s.difficult))difficult++;if(isMarked_(s))starred++;if(mathsIsWeakV20_(q,state,profiles))weak++;if(mathsIsHardV20_(q,state,profiles))hard++});
  const total=(pool||[]).length;return {total,attempted,unseen:Math.max(0,total-attempted),coverage:mathsPctV9_(attempted,total),wrong,difficult,starred,weak,hard,wrongPct:mathsPctV9_(wrong,attempted),difficultPct:mathsPctV9_(difficult,attempted),starredPct:mathsPctV9_(starred,attempted)};
}
function mathsGroupV9_(chapter){const x=String(chapter||'').toLowerCase();if(/fraction pattern|triplet|calculation memory|square|cube/.test(x))return'misc';if(/percentage|profit|loss|discount|ratio|proportion|average|mixture|alligation|interest|time.*work|pipe|cistern|speed|distance|train|boat|stream|partnership|ages|work.*wage/.test(x))return'arithmetic';return'advanced'}
function mathsNewestKeyV9_(q){const raw=q.date_added||q.created_at||q.added_at||q.timestamp||q.updated_at||'';const t=new Date(raw).getTime();return Number.isFinite(t)&&t>0?t:0}
function mathsNewPoolV9_(pool,state){
  const unseen=(pool||[]).filter(q=>Number((state[String(q.question_id)]||{}).attempts||0)===0),dated=unseen.map(mathsNewestKeyV9_).filter(Boolean),max=dated.length?Math.max.apply(null,dated):0,cut=max?max-MATHS_NEW_WINDOW_DAYS*86400000:0;
  return unseen.filter(q=>{const t=mathsNewestKeyV9_(q);return !max||!t||t>=cut}).sort((a,b)=>mathsNewestKeyV9_(b)-mathsNewestKeyV9_(a)||String(b.question_id).localeCompare(String(a.question_id)));
}
function mathsWeakRankV9_(pool,state){
  return mathsWeakRankV20_(pool||[],state||mathsStateMapV9_(),mathsAttemptProfileMapV20_(false));
}
function mathsStarLogV9_(){ensureMathsV3_();return ensureMathsV3_()}
function mathsRevisionMembershipV9_(){
  const history={},days={};sheetObjects_(mathsStarLogV9_()).filter(r=>['IMPORTANT','DIFFICULT'].includes(String(r.type||'').toUpperCase())&&String(r.action||'').toUpperCase()==='ON').forEach(r=>{const id=String(r.question_id||'').trim(),day=Math.max(1,Number(r.study_day||1));if(!id)return;history[id]=true;(days[day]||(days[day]={}))[id]=true});
  const current=mathsCurrentRevisionIdsV20_(mathsQuestionMapV9_(),mathsStateMapV9_());return {membership:current,current:current,history:history,days:days};
}
function mathsConceptIdsV9_(){const out={};sheetObjects_(ensureConceptsV4_()).forEach(r=>{const id=String(r.question_id||'').trim();if(id&&(!Object.prototype.hasOwnProperty.call(r,'active')||bool_(r.active)))out[id]=true});return out}
function mathsScopePoolV9_(request){
  request=request||{};const scope=String(request.scope||'all').toLowerCase(),chapter=String(request.chapter||''),topic=String(request.majorTopic||request.majorTopicKey||''),chapters=(request.chapters||[]).map(String),map=mathsQuestionMapV9_();let all=mathsStudyQuestionsV9_();
  if(scope==='demand_set'){const set=getDemandSetById_(String(request.setId||''));if(!set)return[];return json_(set.question_ids_json,[]).map(id=>map[String(id)]).filter(Boolean)}
  if(scope==='revision_current'){const ids=mathsRevisionMembershipV9_().current;return Object.keys(ids).map(id=>map[id]).filter(Boolean)}
  if(scope==='star_history'){const x=mathsRevisionMembershipV9_(),lo=Number(request.starLo||1),hi=Number(request.starHi||999999),ids={};Object.keys(x.days).map(Number).filter(d=>d>=lo&&d<=hi).forEach(d=>Object.keys(x.days[d]||{}).forEach(id=>ids[id]=true));return Object.keys(ids).map(id=>map[id]).filter(Boolean)}
  if(scope==='new_practice'){let pool=mathsNewPoolV9_(mathsStudyQuestionsV9_(),mathsStateMapV9_());if(chapter)pool=pool.filter(q=>chapterMatchesPlan_(q.chapter,chapter));return pool}
  if(scope==='concept_saved'){const ids=mathsConceptIdsV9_();all=Object.keys(ids).map(id=>map[id]).filter(Boolean);if(chapter)all=all.filter(q=>chapterMatchesPlan_(q.chapter,chapter));return all}
  return all.filter(q=>{if(scope==='chapter'&&chapter&&!chapterMatchesPlan_(q.chapter,chapter))return false;if(scope==='topic'){if(chapter&&!chapterMatchesPlan_(q.chapter,chapter))return false;const key=typeof majorTopicForQuestion_==='function'?majorTopicForQuestion_(q):String(q.topic||'');if(topic&&normalizeLabel_(key)!==normalizeLabel_(topic)&&majorTopicKey_(key)!==String(topic)&&normalizeLabel_(q.topic)!==normalizeLabel_(topic))return false}if(scope==='group'&&chapters.length&&!chapters.some(c=>chapterMatchesPlan_(q.chapter,c)))return false;return true})
}
function mathsAvoidRepeatOptionV9_(payload,state){
  if(!payload||!Array.isArray(payload.questions))return payload;const conceptIds=mathsConceptIdsV9_();payload.questions.forEach(q=>{const s=state[String(q.questionId)]||{};q.important=isMarked_(s);q.marked=isMarked_(s);q.difficult=bool_(s.difficult);q.inConcept=!!conceptIds[String(q.questionId)];if(q.answerMode!=='MCQ'||!Array.isArray(q.options)||q.options.length<2)return;const avoid=String(s.last_correct_option||'').toUpperCase();if(!avoid||String(q.correctOption||'').toUpperCase()!==avoid)return;const keys=q.options.map(o=>String(o.key)),ci=keys.indexOf(q.correctOption);const choices=keys.map((_,i)=>i).filter(i=>i!==ci);if(ci<0||!choices.length)return;const si=choices[Math.floor(Math.random()*choices.length)],tmp=q.options[ci].text;q.options[ci].text=q.options[si].text;q.options[si].text=tmp;q.correctOption=q.options[si].key});return payload;
}
function makeMathsSessionV9_(pool,request,label){
  const state=mathsStateMapV9_(),sessionId=Utilities.getUuid(),base=String(request.title||request.chapter||request.groupName||'Maths'),title=base+' · '+label,mode='maths_'+String(request.kind||'practice'),payload=mathsAvoidRepeatOptionV9_(sessionPayload_(sessionId,pool,state,title,mode,0,null),state);saveSession_({session_id:sessionId,mode,title,question_ids_json:JSON.stringify(pool.map(q=>q.question_id)),current_index:0,updated_at:new Date(),completed:false,params_json:JSON.stringify(request),rendered_questions_json:JSON.stringify(payload.questions||[])});return payload;
}
function startMathsPracticeV9(request){
  ensureMathsV3_();request=Object.assign({},request||{});const state=mathsStateMapV9_(),kind=String(request.kind||'random').toLowerCase(),scope=String(request.scope||'all').toLowerCase(),count=Math.max(1,Math.min(100,Number(request.count||20)));let pool=mathsScopePoolV9_(request),label='Random';
  if(kind==='all'){if(scope==='star_history'||scope==='revision_current')pool=pool.filter(q=>!isMastered_(state[String(q.question_id)]));pool=shuffle_(pool);label='Practice All'}
  else if(kind==='new'){pool=mathsNewPoolV9_(pool,state).slice(0,count);label='New'}
  else if(kind==='weak'){pool=mathsWeakRankV9_(pool,state).slice(0,count);label='Weak'}
  else if(kind==='hard'){pool=mathsHardRankV20_(pool,state,mathsAttemptProfileMapV20_(false)).slice(0,count);label='Hard'}
  else if(kind==='starred'||kind==='important'){pool=shuffle_(pool.filter(q=>isMarked_(state[String(q.question_id)])&&!isMastered_(state[String(q.question_id)]))).slice(0,count);label='Starred'}
  else if(kind==='difficult'){pool=shuffle_(pool.filter(q=>bool_((state[String(q.question_id)]||{}).difficult)&&!isMastered_(state[String(q.question_id)]))).slice(0,count);label='Difficult'}
  else {pool=shuffle_(pool.filter(q=>!isMastered_(state[String(q.question_id)]))).slice(0,count);label='Random'}
  if(!pool.length)return {ok:false,message:'No eligible '+label.toLowerCase()+' questions found for this selection.'};return makeMathsSessionV9_(pool,request,label)
}
function getMathsScopeMetricV9(request){return Object.assign({version:mathsVersionV9_()},mathsMetricV9_(mathsScopePoolV9_(request||{}),mathsStateMapV9_()))}
function buildMathsSnapshotV9_(){
  const version=mathsVersionV9_(),state=mathsStateMapV9_(),all=mathsStudyQuestionsV9_(),by={};all.forEach(q=>{const c=String(q.chapter||'Other');(by[c]||(by[c]=[])).push(q)});const chapters=Object.keys(by).sort().map(chapter=>({chapter,group:mathsGroupV9_(chapter),metric:mathsMetricV9_(by[chapter],state)}));return {version,generatedAt:new Date().toISOString(),overall:mathsMetricV9_(all,state),advanced:mathsMetricV9_(all.filter(q=>mathsGroupV9_(q.chapter)==='advanced'),state),arithmetic:mathsMetricV9_(all.filter(q=>mathsGroupV9_(q.chapter)==='arithmetic'),state),misc:mathsMetricV9_(all.filter(q=>mathsGroupV9_(q.chapter)==='misc'),state),chapters}
}
function getMathsSnapshotV9(force){const c=mathsCacheV9_(),key=mathsCacheKeyV9_('progress');if(!force){const raw=c.get(key);if(raw)try{return JSON.parse(raw)}catch(e){}}const out=buildMathsSnapshotV9_();try{c.put(key,JSON.stringify(out),MATHS_CORE_CACHE_SEC)}catch(e){}return out}
function getMathsNewHubV9(){const snap=getMathsSnapshotV9(false),state=mathsStateMapV9_(),newPool=mathsNewPoolV9_(mathsStudyQuestionsV9_(),state),by={};newPool.forEach(q=>{const c=String(q.chapter||'Other');(by[c]||(by[c]=[])).push(q)});return {version:snap.version,generatedAt:new Date().toISOString(),overall:mathsMetricV9_(newPool,state),chapters:Object.keys(by).sort().map(chapter=>({chapter,metric:mathsMetricV9_(by[chapter],state)}))}}
function mathsRevisionStatsV9_(ids,state){ids=Object.keys(ids||{});const mastered=ids.filter(id=>isMastered_(state[id])).length;return {starred:ids.length,mastered,focus:ids.length-mastered,difficult:ids.filter(id=>bool_((state[id]||{}).difficult)).length}}
function mathsCurrentRevisionStatsV20_(ids,state){ids=Object.keys(ids||{});const mastered=ids.filter(id=>isMastered_(state[id])).length,starred=ids.filter(id=>isMarked_(state[id])).length,difficult=ids.filter(id=>bool_((state[id]||{}).difficult)).length;return {starred, difficult, total:ids.length, mastered, focus:ids.length-mastered}}
function getStarredRevisionV9(){
  const state=mathsStateMapV9_(),x=mathsRevisionMembershipV9_(),days=x.days,currentDay=mathsV3Day_(),dayRows=Object.keys(days).map(Number).sort((a,b)=>b-a).map(day=>({day,stats:mathsRevisionStatsV9_(days[day],state)})),blockStart=Math.floor((currentDay-1)/10)*10+1,recentDays=dayRows.filter(d=>d.day>=blockStart&&d.day<=currentDay),monthStart=Math.floor((currentDay-1)/30)*30+1,tenBlocks=[];
  for(let hi=blockStart-1;hi>=monthStart;hi-=10){const lo=Math.max(monthStart,hi-9),members={};Object.keys(days).map(Number).filter(d=>d>=lo&&d<=hi).forEach(d=>Object.keys(days[d]||{}).forEach(id=>members[id]=true));if(Object.keys(members).length)tenBlocks.push({lo,hi,stats:mathsRevisionStatsV9_(members,state)})}
  const months=[];for(let hi=monthStart-1;hi>=1;hi-=30){const lo=Math.max(1,hi-29),members={};Object.keys(days).map(Number).filter(d=>d>=lo&&d<=hi).forEach(d=>Object.keys(days[d]||{}).forEach(id=>members[id]=true));if(Object.keys(members).length)months.push({lo,hi,label:'Month '+(Math.floor((lo-1)/30)+1),stats:mathsRevisionStatsV9_(members,state)})}
  return {version:mathsVersionV9_(),generatedAt:new Date().toISOString(),currentDay,stats:mathsCurrentRevisionStatsV20_(x.current,state),historyStats:mathsRevisionStatsV9_(x.history,state),recentDays,tenBlocks,months}
}
function getStarredRevisionGroupV9(lo,hi){const state=mathsStateMapV9_(),x=mathsRevisionMembershipV9_();return {days:Object.keys(x.days).map(Number).filter(d=>d>=Number(lo)&&d<=Number(hi)).sort((a,b)=>b-a).map(day=>({day,label:'Day '+day,stats:mathsRevisionStatsV9_(x.days[day],state)}))}}
function getConceptsHubV9(){const map=mathsQuestionMapV9_(),ids=mathsConceptIdsV9_(),state=mathsStateMapV9_(),pool=Object.keys(ids).map(id=>map[id]).filter(Boolean),by={};pool.forEach(q=>{const c=String(q.chapter||'Other');(by[c]||(by[c]=[])).push(q)});return {version:mathsVersionV9_(),generatedAt:new Date().toISOString(),metric:mathsMetricV9_(pool,state),chapters:Object.keys(by).sort().map(chapter=>({chapter,metric:mathsMetricV9_(by[chapter],state)}))}}
function getMathsViewItemsV9(request){const state=mathsStateMapV9_();return mathsScopePoolV9_(request||{}).map(q=>{const s=state[String(q.question_id)]||{},served=serveQuestion_(q,s,getNotesMap_()[String(q.question_id)]||'');return {id:String(q.question_id),chapter:q.chapter||'',topic:q.topic||'',subtopic:q.subtopic||'',prompt:served.prompt||q.prompt||'',options:served.options||[],correctOption:served.correctOption||'',answer:served.answer||q.answer||'',explanation:served.explanation||q.explanation||'',memoryCue:served.memoryCue||q.memory_cue||'',sourceFile:q.source_file||'',sourcePage:q.source_page||'',starred:isMarked_(s),difficult:bool_(s.difficult),attempts:Number(s.attempts||0),wrong:normalizeLabel_(s.last_result)==='wrong'}})}
function toggleStarredV9(questionId,sessionId){return mathsLockedV9_(()=>{const q=mathsRequireQuestionContextV20_(questionId,sessionId),id=String(q.question_id),cur=mathsStateMapV9_()[id]||{},next=!isMarked_(cur),st=upsertState_(id,{marked:next});logMathsV3Flag_(id,'IMPORTANT',next,sessionId);bumpMathsVersionV9_();return {ok:true,questionId:id,important:!!st.marked,difficult:bool_((mathsStateMapV9_()[id]||{}).difficult)}})}
function toggleDifficultV9(questionId,sessionId){return mathsLockedV9_(()=>{const q=mathsRequireQuestionContextV20_(questionId,sessionId),id=String(q.question_id);ensureMathsV3_();const sh=getSheet_(MATHS.SHEETS.STATE),headers=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(key_),col=headers.indexOf('difficult')+1;if(col<1)throw new Error('Difficult state column missing');let rows=sheetObjects_(sh).filter(r=>String(r.question_id||'').trim()===id);if(!rows.length){upsertState_(id,{});rows=sheetObjects_(sh).filter(r=>String(r.question_id||'').trim()===id)}const next=!rows.some(r=>bool_(r.difficult));rows.forEach(r=>sh.getRange(r.__row,col).setValue(next));logMathsV3Flag_(id,'DIFFICULT',next,sessionId);bumpMathsVersionV9_();return {ok:true,questionId:id,important:isMarked_(mathsStateMapV9_()[id]),difficult:next}})}
function toggleConceptV9(questionId,sessionId){return mathsLockedV9_(()=>{const q=mathsRequireQuestionContextV20_(questionId,sessionId),id=String(q.question_id),sh=ensureConceptsV4_(),rows=sheetObjects_(sh),active=rows.filter(r=>String(r.question_id||'').trim()===id&&(!Object.prototype.hasOwnProperty.call(r,'active')||bool_(r.active)));let inConcept;if(active.length){active.forEach(r=>updateSheetObject_(sh,r.__row,{active:false}));inConcept=false}else{appendSheetObject_(sh,{question_id:id,added_at:new Date(),study_day:mathsV3Day_(),chapter:q.chapter||'',topic:q.topic||'',session_id:String(sessionId||''),active:true});inConcept=true}bumpMathsVersionV9_();return {ok:true,questionId:id,inConcept}})}
function mathsChaptersV9_(){const all=mathsStudyQuestionsV9_(),state=mathsStateMapV9_(),map={};all.forEach(q=>{const c=String(q.chapter||'Other').trim()||'Other';if(!map[c])map[c]={chapter:c,total:0,mastered:0,remaining:0,majorMap:{}};const m=map[c];m.total++;const mastered=isMastered_(state[String(q.question_id)]);if(mastered)m.mastered++;else m.remaining++;const name=majorTopicForQuestion_(q),key=majorTopicKey_(name);if(!m.majorMap[key])m.majorMap[key]={key,name,total:0,mastered:0,active:0};m.majorMap[key].total++;if(mastered)m.majorMap[key].mastered++;else m.majorMap[key].active++});return Object.values(map).map(m=>{const order=majorTopicOrder_(m.chapter);m.majorTopics=Object.values(m.majorMap).sort((a,b)=>{const ai=order.indexOf(a.name),bi=order.indexOf(b.name);if(ai>=0||bi>=0)return(ai<0?999:ai)-(bi<0?999:bi)||a.name.localeCompare(b.name);return a.name.localeCompare(b.name)});delete m.majorMap;return m}).sort((a,b)=>a.chapter.localeCompare(b.chapter))}
function mathsDashboardV9_(){const all=mathsStudyQuestionsV9_(),state=mathsStateMapV9_(),scheduled=getScheduledPlan_(),today=scheduled.chapter,core=scheduled.ready?all.filter(q=>chapterMatchesPlan_(q.chapter,today)&&rotationTier_(q)==='Core'):[],masteredToday=core.filter(q=>isMastered_(state[String(q.question_id)])).length;let mastered=0,marked=0,attempted=0;all.forEach(q=>{const s=state[String(q.question_id)]||{};if(isMastered_(s))mastered++;if(isMarked_(s))marked++;if(Number(s.attempts||0)>0)attempted++});return {day:scheduled.day,todayChapter:today,scheduleReady:!!scheduled.ready,total:all.length,chapterTotal:core.length,chapterRemaining:core.length-masteredToday,chapterMastered:masteredToday,freshRemaining:core.filter(q=>!isMastered_(state[String(q.question_id)])&&Number((state[String(q.question_id)]||{}).attempts||0)===0).length,mastered,marked,attempted,generated:getGeneratedQuestions_().filter(active_).length,fractions:all.filter(q=>same_(q.chapter,'Fraction Patterns')).length,triplets:all.filter(q=>same_(q.chapter,'Triplets')).length,activeAll:all.length,pending:scheduled.ready?getPendingPlanDays_(scheduled.day,all,state):[],studyTimezone:scheduled.timezone,planStartDate:scheduled.startDate}}
function mathsLibraryCountsV9_(){const all=mathsStudyQuestionsV9_(),state=mathsStateMapV9_(),ids=new Set(all.map(q=>String(q.question_id))),notes=sheetObjects_(getSheet_(MATHS.SHEETS.NOTES)).filter(n=>String(n.note||'').trim()&&ids.has(String(n.question_id||'')));return {formulas:all.filter(q=>normalizeLabel_(q.card_type)==='formula').length,methods:all.filter(q=>['method','pattern','trap'].includes(normalizeLabel_(q.card_type))).length,fractions:all.filter(q=>same_(q.chapter,'Fraction Patterns')).length,triplets:all.filter(q=>same_(q.chapter,'Triplets')).length,marked:all.filter(q=>isMarked_(state[String(q.question_id)])).length,notes:notes.length,recent:Math.min(20,all.length)}}
function getSafeResumeSessionV9_(){const valid=new Set(Object.keys(mathsQuestionMapV9_())),rows=sheetObjects_(getSheet_(MATHS.SHEETS.SESSIONS)).filter(r=>r.session_id&&!bool_(r.completed)).sort((a,b)=>dateMs_(b.updated_at)-dateMs_(a.updated_at));for(const s of rows){const ids=json_(s.question_ids_json,[]).map(String);if(ids.some(id=>valid.has(id)))return {sessionId:String(s.session_id),title:String(s.title||'Practice'),currentIndex:Math.max(0,Math.min(Number(s.current_index||0),Math.max(0,ids.length-1))),total:ids.length,mode:s.mode}}return null}
function getAppBootstrapV9(){ensureMathsInfrastructure_();return {title:MATHS.TITLE,dashboard:mathsDashboardV9_(),chapters:mathsChaptersV9_(),library:mathsLibraryCountsV9_(),resume:getSafeResumeSessionV9_(),demandSets:getDemandSets_(),settings:getSettingsObject_(),version:mathsVersionV9_()}}
function getMathsHomeV9(){const snap=getMathsSnapshotV9(false),newHub=getMathsNewHubV9(),schedule=getScheduledPlan_(),target=Math.max(1,Number((getPlanEntry_(schedule.day)||{}).targetPerDay||getSetting_('daily_chapter_size',20)||20)),sessions=sheetObjects_(getSheet_(MATHS.SHEETS.SESSIONS)).filter(r=>normalizeLabel_(r.mode)==='daily').sort((a,b)=>dateMs_(b.updated_at)-dateMs_(a.updated_at));let daily=null;for(const row of sessions){const p=json_(row.params_json,{});if(Number(p.planDay||0)===Number(schedule.day||0)){daily=row;break}}const done=daily?(bool_(daily.completed)?target:Math.max(0,Math.min(target,Number(daily.current_index||0)))):0,resume=getSafeResumeSessionV9_(),concepts=getConceptsHubV9();return {version:snap.version,generatedAt:new Date().toISOString(),schedule,daily:{target,done,left:Math.max(0,target-done),completed:done>=target,sessionId:daily?String(daily.session_id||''):''},resume,resumeIsDaily:!!(resume&&daily&&String(resume.sessionId)===String(daily.session_id)),newCount:Number(newHub.overall&&newHub.overall.total||0),starred:Number(snap.overall.starred||0),difficult:Number(snap.overall.difficult||0),concepts:Number(concepts.metric.total||0),pending:(mathsDashboardV9_().pending||[]).slice(0,2),overall:snap.overall}}
