function selectPracticePoolV9_(all,state,request,mode){
  request=request||{};all=(all||mathsStudyQuestionsV9_()).filter(active_);state=state||mathsStateMapV9_();
  const chapter=String(request.chapter||''),topicMode=String(mode).indexOf('topic_')===0,requestedName=topicMode?resolveRequestedMajorTopic_(request):'',requestedKey=topicMode?String(request.majorTopicKey||majorTopicKey_(requestedName)):'';
  let mapped=all.filter(q=>same_(q.chapter,chapter));if(topicMode)mapped=mapped.filter(q=>majorTopicKey_(majorTopicForQuestion_(q))===requestedKey);
  const complete=mode==='chapter'||String(mode).endsWith('_complete'),random=String(mode).endsWith('_random'),weak=String(mode).endsWith('_weak');let pool=complete?mapped:mapped.filter(q=>!isMastered_(state[String(q.question_id)]));const count=Math.max(1,Number(request.count||20));
  if(random)pool=shuffle_(pool).slice(0,Math.min(count,pool.length));if(weak)pool=mathsWeakRankV9_(pool,state).slice(0,Math.min(count,pool.length));if(complete)pool=shuffle_(pool);
  const label=topicMode?(requestedName||requestedKey):chapter,title=label+(complete?' · Complete Bank':random?' · Random Practice':' · Weak Practice');return {pool,title,majorTopic:requestedName,mappedTotal:mapped.length,eligibleTotal:pool.length};
}
function selectGroupPracticeV9_(all,generated,state,request,mode){
  request=request||{};state=state||mathsStateMapV9_();const complete=String(mode).endsWith('_complete'),random=String(mode).endsWith('_random'),weak=String(mode).endsWith('_weak'),groupName=String(request.groupName||request.group||'Practice Group'),chapters=(request.chapters||[]).map(x=>normalizeLabel_(x)).filter(Boolean),source=String(request.source||'questions');let pool=[];
  if(source==='generated')pool=(generated||[]).filter(q=>active_(q)&&(!request.generatedChapter||same_(q.chapter,request.generatedChapter))&&(!request.generatedTopic||same_(q.topic,request.generatedTopic)));
  else pool=(all||mathsStudyQuestionsV9_()).filter(q=>active_(q)&&chapters.includes(normalizeLabel_(q.chapter)));
  if(!complete)pool=pool.filter(q=>!isMastered_(state[String(q.question_id)]));const count=Math.max(1,Number(request.count||20));if(random)pool=shuffle_(pool).slice(0,Math.min(count,pool.length));if(weak)pool=mathsWeakRankV9_(pool,state).slice(0,Math.min(count,pool.length));if(complete)pool=shuffle_(pool);return {pool,title:groupName+' · '+(complete?'Practice All':random?'Random Practice':'Weak Practice')};
}
function filterLibraryV9_(all,state,cluster){
  const pool=(all||mathsStudyQuestionsV9_()).filter(active_),c=String(cluster||'').toLowerCase();if(c==='formula'||c==='formulas')return pool.filter(q=>normalizeLabel_(q.card_type)==='formula');if(c==='methods')return pool.filter(q=>['method','pattern','trap'].includes(normalizeLabel_(q.card_type)));if(c==='fractions')return pool.filter(q=>same_(q.chapter,'Fraction Patterns'));if(c==='triplets')return pool.filter(q=>same_(q.chapter,'Triplets'));if(c==='marked')return pool.filter(q=>isMarked_(state[String(q.question_id)]));if(c==='notes'){const ids=new Set(sheetObjects_(getSheet_(MATHS.SHEETS.NOTES)).filter(n=>String(n.note||'').trim()).map(n=>String(n.question_id)));return pool.filter(q=>ids.has(String(q.question_id)))}if(c==='recent')return pool.slice().sort((a,b)=>mathsNewestKeyV9_(b)-mathsNewestKeyV9_(a)).slice(0,20);return pool;
}
function filterOnDemandV9_(all,state,request){request=request||{};return (all||mathsStudyQuestionsV9_()).filter(active_).filter(q=>{if(request.chapter&&!same_(q.chapter,request.chapter))return false;if(request.topic&&!same_(q.topic,request.topic))return false;if(request.subtopic&&!same_(q.subtopic,request.subtopic))return false;if(request.cardType&&!same_(q.card_type,request.cardType))return false;if(request.difficulty&&!same_(q.difficulty,request.difficulty))return false;if(request.markedOnly&&!isMarked_(state[String(q.question_id)]))return false;if(request.activeOnly&&isMastered_(state[String(q.question_id)]))return false;if(request.masteredOnly&&!isMastered_(state[String(q.question_id)]))return false;return true})}
