const MATHS_INTEGRITY_VERSION='v20';
const MATHS_EXTERNAL_FINGERPRINT_CACHE_SEC=20;
const MATHS_RESUME_MAX_AGE_MS=72*60*60*1000;

function mathsBankKeyV18_(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'');}
function mathsCanonicalSchemaV18_(){return {
  Questions:['Question_ID','Chapter','Topic','Subtopic','Card_Type','Prompt','Answer','Explanation','Memory_Cue','Difficulty','Marked_Default','Mastered_Default','Diagram_Type','Diagram_JSON','Source_File','Source_Page','Source_URL','Status','Answer_Mode','Option_A','Option_B','Option_C','Option_D','Correct_Option','Template_Group','Variant_Types','Rotation_Tier','Practice_Bank','Added_At'],
  State:['Question_ID','Attempts','Mastered','Marked','Last_Attempt','Last_Result','Last_Response_Sec','Chapter','Topic','Subtopic','Last_Variant','Last_Correct_Option','Difficult'],
  Attempts:['Attempt_ID','Timestamp','Question_ID','Result','Response_Sec','Mode','Session_ID','Mastered_After','Marked_After','Variant_Type','Selected_Option','Question_Index','Client_Attempt_Key'],
  Sessions:['Session_ID','Mode','Title','Question_IDs_JSON','Current_Index','Updated_At','Completed','Params_JSON','Rendered_Questions_JSON'],
  Concepts:['Question_ID','Added_At','Study_Day','Chapter','Topic','Session_ID','Active'],
  Demand_Sets:['Set_ID','Set_Name','Description','Question_IDs_JSON','Status','Created_At'],
  Generated_Practice:['Question_ID','Chapter','Topic','Subtopic','Card_Type','Prompt','Answer','Explanation','Memory_Cue','Difficulty','Marked_Default','Mastered_Default','Diagram_Type','Diagram_JSON','Source_File','Source_Page','Source_URL','Status','Answer_Mode','Option_A','Option_B','Option_C','Option_D','Correct_Option','Template_Group','Variant_Types','Rotation_Tier','Practice_Bank','Added_At'],
  Settings:['Key','Value'],Chapter_Plan:['Order','Chapter','Target_Per_Day','Status','Introduced','Mastered']};}
function ensureMathsCanonicalSchemaV18_(){const ss=SpreadsheetApp.getActive(),s=mathsCanonicalSchemaV18_();Object.keys(s).forEach(n=>ensureSheet_(ss,n,s[n]));return validateMathsCanonicalSchemaV18_();}
function validateMathsCanonicalSchemaV18_(){const ss=SpreadsheetApp.getActive(),s=mathsCanonicalSchemaV18_(),sheets={};let ok=true;Object.keys(s).forEach(n=>{const sh=ss.getSheetByName(n),actual=sh&&sh.getLastColumn()?sh.getRange(1,1,1,sh.getLastColumn()).getDisplayValues()[0].map(String):[],missing=s[n].filter(h=>actual.indexOf(h)<0);if(!sh||missing.length)ok=false;sheets[n]={exists:!!sh,missing:missing,extra:actual.filter(h=>s[n].indexOf(h)<0)};});return {ok:ok,version:MATHS_INTEGRITY_VERSION,sheets:sheets};}

function mathsVisibleDataFingerprintV18_(force){const c=CacheService.getScriptCache(),key='maths:v20:visible-data-fingerprint';if(!force){const hit=c.get(key);if(hit)return hit;}const ss=SpreadsheetApp.getActive(),parts=[];['Questions','Concepts','Demand_Sets','Generated_Practice','Chapter_Plan','Settings'].forEach(n=>{const sh=ss.getSheetByName(n);if(!sh){parts.push([n,'MISSING']);return;}const r=sh.getLastRow(),col=sh.getLastColumn();parts.push([n,r,col,r&&col?sh.getRange(1,1,r,col).getDisplayValues():[]]);});const raw=JSON.stringify(parts),d=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,raw,Utilities.Charset.UTF_8),fp=Utilities.base64EncodeWebSafe(d).replace(/=+$/,'');try{c.put(key,fp,MATHS_EXTERNAL_FINGERPRINT_CACHE_SEC)}catch(e){}return fp;}

function mathsContentTimestampReconcileV20_(){
  const props=PropertiesService.getScriptProperties(),first=props.getProperty('MATHS_CONTENT_TIMESTAMPS_V20')!=='1',stamp=first?new Date('2000-01-01T00:00:00Z'):new Date();let stamped=0;
  [MATHS.SHEETS.QUESTIONS,MATHS.SHEETS.GENERATED].forEach(name=>{const sh=getSheet_(name),meta=sheetHeaderMap_(sh),col=meta.map.added_at;if(!col||sh.getLastRow()<2)return;const range=sh.getRange(2,col,sh.getLastRow()-1,1),values=range.getValues(),ids=sh.getRange(2,meta.map.question_id,sh.getLastRow()-1,1).getValues();let changed=false;values.forEach((row,i)=>{if(String(ids[i][0]||'').trim()&&!row[0]){row[0]=stamp;stamped++;changed=true}});if(changed)range.setValues(values)});
  props.setProperty('MATHS_CONTENT_TIMESTAMPS_V20','1');return {stamped:stamped,baseline:first};
}

function mathsConceptRegistryReconcileV18_(){const questions=getAllQuestions_(),qMap={},dedicated={};questions.forEach(q=>{const id=String(q.question_id||'').trim();if(!id)return;qMap[id]=q;if(active_(q)&&mathsBankKeyV18_(q.practice_bank)==='CONCEPTS')dedicated[id]=q;});const sh=ensureConceptsV4_(),rows=sheetObjects_(sh),activeRows={};rows.forEach(r=>{const id=String(r.question_id||'').trim();if(id&&(!Object.prototype.hasOwnProperty.call(r,'active')||bool_(r.active)))(activeRows[id]||(activeRows[id]=[])).push(r);});let added=0,deactivatedOrphans=0;Object.keys(dedicated).forEach(id=>{if(activeRows[id]&&activeRows[id].length)return;const q=dedicated[id];sh.appendRow([id,new Date(),mathsV3Day_(),q.chapter||'',q.topic||'','dedicated-concept-sync-v18',true]);added++;});Object.keys(activeRows).forEach(id=>{const q=qMap[id];if(q&&active_(q))return;activeRows[id].forEach(r=>{sh.getRange(r.__row,7).setValue(false);deactivatedOrphans++;});});if(added||deactivatedOrphans){try{CacheService.getScriptCache().remove('maths:v18:visible-data-fingerprint')}catch(e){}}return {addedDedicated:added,deactivatedOrphans:deactivatedOrphans,preservedSavedAcademic:true};}

function syncMathsExternalDataV18(){ensureMathsCanonicalSchemaV18_();return mathsLockedV9_(()=>{const p=PropertiesService.getScriptProperties(),timestamps=mathsContentTimestampReconcileV20_(),before=mathsVisibleDataFingerprintV18_(!!timestamps.stamped),previous=String(p.getProperty('MATHS_VISIBLE_DATA_FINGERPRINT_V18')||''),changed=!!timestamps.stamped||!previous||previous!==before;let conceptSync={addedDedicated:0,deactivatedOrphans:0,preservedSavedAcademic:true};if(changed)conceptSync=mathsConceptRegistryReconcileV18_();const after=(conceptSync.addedDedicated||conceptSync.deactivatedOrphans)?mathsVisibleDataFingerprintV18_(true):before;let version=mathsVersionV9_();if(changed){version=bumpMathsVersionV9_();p.setProperty('MATHS_VISIBLE_DATA_FINGERPRINT_V18',after);}return {ok:true,changed:changed,version:String(version),fingerprint:after,conceptSync:conceptSync,timestamps:timestamps,generatedAt:new Date().toISOString()};});}

function mathsResumeCandidateV18_(s,valid,currentDay,now){if(!s||!s.session_id||bool_(s.completed))return false;const ids=json_(s.question_ids_json,[]).map(String),index=Math.max(0,Number(s.current_index||0));if(!ids.length||index>=ids.length||!ids.slice(index).some(id=>valid.has(id)))return false;const updated=dateMs_(s.updated_at),age=updated?Math.max(0,now-updated):Infinity,mode=normalizeLabel_(s.mode||''),params=json_(s.params_json,{});if(mode==='daily')return Number(params.planDay||0)===Number(currentDay||0)&&age<=7*86400000;return age<=MATHS_RESUME_MAX_AGE_MS;}
function getMathsResumePolicyV18(){const valid=new Set(Object.keys(mathsQuestionMapV9_())),currentDay=Number((getScheduledPlan_()||{}).day||0),now=Date.now(),rows=sheetObjects_(getSheet_(MATHS.SHEETS.SESSIONS)).filter(r=>r.session_id&&!bool_(r.completed)).sort((a,b)=>dateMs_(b.updated_at)-dateMs_(a.updated_at)),selected=rows.find(s=>mathsResumeCandidateV18_(s,valid,currentDay,now))||null;const resume=selected?{sessionId:String(selected.session_id),title:String(selected.title||'Practice'),currentIndex:Math.max(0,Number(selected.current_index||0)),total:json_(selected.question_ids_json,[]).length,mode:selected.mode}:null;return {ok:true,resume:resume,ignoredStale:rows.filter(s=>!mathsResumeCandidateV18_(s,valid,currentDay,now)).length,currentDay:currentDay};}
function getMathsStartupPayloadV18(){const sync=syncMathsExternalDataV18(),bootstrap=getAppBootstrapV14(),home=getMathsHomeV14(),policy=getMathsResumePolicyV18();home.resume=policy.resume;home.resumeIsDaily=!!(policy.resume&&home.daily&&String(policy.resume.sessionId)===String(home.daily.sessionId||''));return {ok:true,version:String(sync.version||home.version||bootstrap.version||''),cacheSchema:'academic-v20-cache1',compat:'v14',bootstrap:bootstrap,home:home,resumePolicy:policy,externalSync:sync,generatedAt:new Date().toISOString()};}

function mathsDupMapV18_(rows,key){const m={},d={};(rows||[]).forEach(r=>{const id=String(r[key]||'').trim();if(id)(m[id]||(m[id]=[])).push(Number(r.__row||0));});Object.keys(m).forEach(id=>{if(m[id].length>1)d[id]=m[id];});return d;}
function mathsOptV18_(q,k){return String(q['option_'+String(k||'').toLowerCase()]||'').trim();}
function mathsSetExpectedV18_(setId,q){const id=String(q&&q.question_id||''),bank=mathsBankKeyV18_(q&&q.practice_bank),tpl=String(q&&q.template_group||'').trim().toUpperCase();if(setId==='MOCK_QUESTIONS')return /^MQ\d+$/.test(id)&&bank==='MOCK'&&tpl==='MOCK_QUESTIONS';if(setId==='MOCK_FORMULA_REVISION')return /^MFR\d+$/.test(id)&&bank==='MOCK_FORMULA_REVISION'&&tpl==='MOCK_FORMULA_REVISION';if(setId===MATHS.CALC_SET_ID)return /^CT\d+$/.test(id)&&bank==='CALCULATION'&&(tpl==='CALC_TRAINING'||/^CALC_DAY/.test(tpl));return true;}
function mathsHasStoredOptionsV18_(q){return ['A','B','C','D'].some(k=>!!mathsOptV18_(q,k))||!!String(q.correct_option||'').trim();}
function mathsComparableAnswerV20_(v){return normalizeLabel_(String(v||'').replace(/₹|rs\.?|rupees?/gi,'').replace(/\(\s*approx\.?\s*\)|approx\.?/gi,'').replace(/\s*([:,%])\s*/g,'$1').replace(/,/g,'').trim());}
function mathsRuntimeQuestionValidV20_(q){const id=String(q&&q.question_id||'').trim(),mode=String(q&&q.answer_mode||'').trim().toUpperCase();if(!id||!active_(q)||!String(q.prompt||'').trim()||!['MCQ','REVEAL'].includes(mode))return false;if(mode==='REVEAL')return !!String(q.answer||'').trim();const correct=String(q.correct_option||'').trim().toUpperCase();return ['A','B','C','D'].includes(correct)&&!!mathsOptV18_(q,correct);}

function auditMathsDataIntegrityV18(){const schema=validateMathsCanonicalSchemaV18_(),questions=sheetObjects_(getSheet_(MATHS.SHEETS.QUESTIONS)).filter(r=>String(r.question_id||'').trim()),generated=sheetObjects_(getSheet_(MATHS.SHEETS.GENERATED)).filter(r=>String(r.question_id||'').trim()),all=questions.concat(generated),qById={};all.forEach(q=>{const id=String(q.question_id||'').trim();if(id&&!qById[id])qById[id]=q;});const duplicateQuestionIds=mathsDupMapV18_(questions,'question_id');
  const conceptRows=sheetObjects_(ensureConceptsV4_()).filter(r=>String(r.question_id||'').trim()),activeConceptRows=conceptRows.filter(r=>!Object.prototype.hasOwnProperty.call(r,'active')||bool_(r.active)),activeConceptSet={};activeConceptRows.forEach(r=>activeConceptSet[String(r.question_id).trim()]=true);const dedicated=questions.filter(q=>active_(q)&&mathsBankKeyV18_(q.practice_bank)==='CONCEPTS'),conceptQuestionMissingRegistry=dedicated.filter(q=>!activeConceptSet[String(q.question_id)]).map(q=>String(q.question_id)),registryMissingQuestion=activeConceptRows.filter(r=>!qById[String(r.question_id)]).map(r=>String(r.question_id)),registryInactiveQuestion=activeConceptRows.filter(r=>qById[String(r.question_id)]&&!active_(qById[String(r.question_id)])).map(r=>String(r.question_id));
  const invalidStatus=[],missingPracticeBank=[],answerModeMismatch=[],invalidCorrectOption=[],blankCorrectOption=[],answerOptionMismatch=[],malformedRows=[];questions.forEach(q=>{const id=String(q.question_id||'').trim(),status=normalizeLabel_(q.status||''),mode=String(q.answer_mode||'').trim().toUpperCase(),bank=mathsBankKeyV18_(q.practice_bank),correct=String(q.correct_option||'').trim().toUpperCase(),stored=mathsHasStoredOptionsV18_(q);if(!['active','inactive'].includes(status))invalidStatus.push(id);if(active_(q)&&!bank)missingPracticeBank.push(id);if(bank==='MOCK_FORMULA_REVISION'&&mode!=='REVEAL')answerModeMismatch.push(id);if(mode==='REVEAL'&&!String(q.answer||'').trim())answerModeMismatch.push(id);if(mode==='MCQ'&&stored){if(!['A','B','C','D'].includes(correct))invalidCorrectOption.push(id);else if(!mathsOptV18_(q,correct))blankCorrectOption.push(id);else if(String(q.answer||'').trim()&&mathsComparableAnswerV20_(q.answer)!==mathsComparableAnswerV20_(mathsOptV18_(q,correct)))answerOptionMismatch.push(id);}if(!mode&&stored)answerModeMismatch.push(id);if(['active','inactive','reveal','mcq'].includes(normalizeLabel_(q.source_url||''))||['active','inactive'].includes(normalizeLabel_(q.answer_mode||''))||['reveal','mcq'].includes(normalizeLabel_(q.status||'')))malformedRows.push(id);});
  const demandSets={};sheetObjects_(getSheet_(MATHS.SHEETS.DEMAND_SETS)).filter(r=>r.set_id&&normalizeLabel_(r.status||'Active')!=='inactive').forEach(r=>{const setId=String(r.set_id),raw=json_(r.question_ids_json,null),badJson=!Array.isArray(raw),ids=Array.isArray(raw)?raw.map(String):[],seen={},dups=[];ids.forEach(id=>{seen[id]=(seen[id]||0)+1;if(seen[id]===2)dups.push(id);});const missing=ids.filter(id=>!qById[id]),inactive=ids.filter(id=>qById[id]&&!active_(qById[id])),wrong=ids.filter(id=>qById[id]&&!mathsSetExpectedV18_(setId,qById[id]));demandSets[setId]={count:ids.length,badJson:badJson,duplicateIds:dups,missingIds:missing,inactiveIds:inactive,wrongCollectionIds:wrong,ok:!badJson&&!dups.length&&!missing.length&&!inactive.length&&!wrong.length};});
  const stateRows=sheetObjects_(getSheet_(MATHS.SHEETS.STATE)).filter(r=>r.question_id),orphanState=stateRows.filter(r=>!qById[String(r.question_id)]).map(r=>String(r.question_id)),duplicateStateIds=mathsDupMapV18_(stateRows,'question_id'),valid=new Set(Object.keys(mathsQuestionMapV9_())),currentDay=Number((getScheduledPlan_()||{}).day||0),now=Date.now(),incomplete=sheetObjects_(getSheet_(MATHS.SHEETS.SESSIONS)).filter(r=>r.session_id&&!bool_(r.completed)),orphanResumableSessions=[],orphanStaleSessions=[];incomplete.forEach(s=>{const missing=json_(s.question_ids_json,[]).map(String).filter(id=>!qById[id]);if(!missing.length)return;const item={sessionId:String(s.session_id),missingIds:missing};if(mathsResumeCandidateV18_(s,valid,currentDay,now))orphanResumableSessions.push(item);else orphanStaleSessions.push(item);});
  const academic=typeof auditMathsFocusedPracticeV14==='function'?auditMathsFocusedPracticeV14():{practiceBankLeak:null,mockLeak:null,calculationLeak:null,conceptLeak:null},circleConceptIds=dedicated.filter(q=>chapterMatchesPlan_(q.chapter,'Geometry')&&normalizeLabel_(q.topic||'')==='circle'&&/^CIRC\d+$/.test(String(q.question_id))).map(q=>String(q.question_id)),circleAcademicIds=questions.filter(q=>active_(q)&&mathsBankKeyV18_(q.practice_bank)==='ACADEMIC'&&chapterMatchesPlan_(q.chapter,'Geometry')&&normalizeLabel_(q.topic||'')==='circle'&&/^CIRQ\d+$/.test(String(q.question_id))).map(q=>String(q.question_id)),mfrIds=['MFR035','MFR036','MFR037','MFR038','MFR039','MFR040','MFR041'],mfrRepairOk=mfrIds.filter(id=>{const q=qById[id];return q&&active_(q)&&String(q.answer_mode||'').toUpperCase()==='REVEAL'&&mathsBankKeyV18_(q.practice_bank)==='MOCK_FORMULA_REVISION';});
  const critical=Object.keys(duplicateQuestionIds).length+Object.keys(mathsDupMapV18_(activeConceptRows,'question_id')).length+conceptQuestionMissingRegistry.length+registryMissingQuestion.length+registryInactiveQuestion.length+invalidStatus.length+missingPracticeBank.length+answerModeMismatch.length+invalidCorrectOption.length+blankCorrectOption.length+malformedRows.length+orphanState.length+orphanResumableSessions.length+Object.keys(duplicateStateIds).length+Object.values(demandSets).filter(x=>!x.ok).length+Number(academic.practiceBankLeak||0)+Number(academic.mockLeak||0)+Number(academic.calculationLeak||0)+Number(academic.conceptLeak||0);
  return {ok:schema.ok&&critical===0,version:MATHS_INTEGRITY_VERSION,generatedAt:new Date().toISOString(),schema:schema,duplicateQuestionIds:duplicateQuestionIds,duplicateQuestionIdCount:Object.keys(duplicateQuestionIds).length,duplicateConceptRegistryIds:mathsDupMapV18_(conceptRows,'question_id'),duplicateActiveConceptIds:mathsDupMapV18_(activeConceptRows,'question_id'),conceptQuestionMissingRegistry:conceptQuestionMissingRegistry,registryMissingQuestion:registryMissingQuestion,registryInactiveQuestion:registryInactiveQuestion,invalidStatus:invalidStatus,missingPracticeBank:missingPracticeBank,answerModeMismatch:Array.from(new Set(answerModeMismatch)),invalidCorrectOption:invalidCorrectOption,blankCorrectOption:blankCorrectOption,answerOptionMismatch:answerOptionMismatch,malformedRows:malformedRows,demandSets:demandSets,orphanState:orphanState,duplicateStateIds:duplicateStateIds,orphanResumableSessions:orphanResumableSessions,orphanStaleSessions:orphanStaleSessions,academic:academic,circleConceptCount:new Set(circleConceptIds).size,circleAcademicCount:new Set(circleAcademicIds).size,mfrRepairOk:mfrRepairOk,mfrRepairCount:mfrRepairOk.length,criticalCount:critical};}
function getMathsRepairStatusV18(){const audit=auditMathsDataIntegrityV18();return {ok:audit.ok,version:MATHS_INTEGRITY_VERSION,cache:syncMathsExternalDataV18(),resume:getMathsResumePolicyV18(),audit:audit};}
